org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.rmi.server.hostname=127.0.0.1 -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.java.home=C:/Users/grzegorz.kotarba/dev/jdk-17.0.19+10
